name: Build, Version, and Release

on:
  push:
    branches:
      - main  # Only trigger on main branch

permissions:
  contents: write  # Required for tagging and creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Up Git User
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: Install Arduino AVR Core
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Prepare
      run: |
        bash prepare.sh

    - name: Build Script
      run: |
        bash build.sh

  build-consumers:
    runs-on: ubuntu-latest
    needs: build  # Only run if the library build passes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare Arduino CLI
      run: |
        bash prepare-arduino-cli.sh
        
    - name: Build Consumers
      run: |
        bash build-consumers.sh

  release:
    runs-on: ubuntu-latest
    needs: [build, build-consumers]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Up Git User
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Run Version Increment Script (Only if Build Succeeds)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Increment version and tag it
        bash version-increment.sh

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(grep -oP 'version=\K.*' library.properties)
        release_name="Release v$version"
        release_body="Automatic release for version v$version"
        
        # Create a release on GitHub
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\":\"v$version\",\"name\":\"$release_name\",\"body\":\"$release_body\",\"draft\":false,\"prerelease\":false}" \
          https://api.github.com/repos/${{ github.repository }}/releases
